project_id = "kubdwbzahemthstrxrxh"

[functions.extract-property-data]
verify_jwt = false

[functions.search-property-photos]
verify_jwt = false

[functions.cleanup-old-creatives]
verify_jwt = false

[functions.autentique-integration]
verify_jwt = false

[functions.autentique-webhook]
verify_jwt = false
